site_name: 'OpenStudio<sup>&reg;</sup> User Docs'
site_favicon: favicon.ico
site_logo: 'OS_32x32.png'

pages:
- [index.md]

- [getting_started/features.md, Getting Started, Current Features]
- [getting_started/roadmap.md, Getting Started, Planned Features]
- [getting_started/getting_started.md, Getting Started, Installation and Introductory Tutorial]

- [tutorials/creating_your_model.md, Essential Tutorials, Creating Your Model]
- [tutorials/running_your_simulation.md, Essential Tutorials, Running Simulations & Viewing Results]
- [tutorials/radiance_tutorial.md, Essential Tutorials, Radiance and OpenStudio]
- [tutorials/tutorial_bcl.md, Essential Tutorials, Building Component Library]

- [tutorials/life_cycle_costing_examples.md, Advanced Tutorials, Life Cycle Cost Analysis]
- [tutorials/tutorial_gbxmlimport.md, Advanced Tutorials, Import gbXML]
- [tutorials/tutorial_shadingcontrols.md, Advanced Tutorials, Shading Controls]
- [tutorials/tutorial_windowproperty_frameanddivider.md, Advanced Tutorials, Window Property Frame and Divider]

- [reference/openstudio_application_interface.md, Reference, OpenStudio Application Interface Guide]
- [reference/sketchup_plugin_interface.md, Reference, SketchUp Plug-in Interface Guide]
- [reference/geometry_editor.md, Reference, FloorspaceJS]
- [reference/openstudio_results_measure.md, Reference, OpenStudio Results Measure]

- [help/troubleshooting.md, Help, Troubleshooting]
- [help/software_license.md, Help, Software License]

theme: simplex
theme_dir: 'bootstrap_nrel'



